### ISSUE TITLE
problem when integrated the project with template material design

### ISSUE THREAD

**Issue by pipeddev** [creativetimofficial/react-webpack-babel-md-tutorial#1]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

the website will should working when do 'npm run webpack', but shows an error in a file .css

# Current Behavior

the console shows an error in file material-dashboard-react.css file located in assets/css

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by einazare** [comment]
Hello there, @fcarrasco92 ,

Could you also paste the error that you are getting?
Also, could you please paste here your package.json?

Best,
Manu
